### PR TITLE
Introduce Editor Config

### PR DESCRIPTION
**Pull request by bogdankharchenko**
Hey guys/gals 👋!

I moved to GVL recently and I am looking to get involved with local geek community and turns out this projects uses laravel, which is something I use daily, figured I'd play around with some code in this repo but I need my spaces vs tabs question solved first. And maybe we figure out how to merge #112 and so I can get invited into the slack channel. 😉 

This is just a simple `.editorconfig` which uses spaces as the indent style to file to get the ball rolling. (laravel/laravel default)

### CODE REVIEW

**Comment by allella** [comment]
Thanks for joining in.

I'll defer to @zach2825 about the configuration file.

The Slack invite form has a free tier limit and we probably either hit that already this month as @soulfire86 determined in #114 

@oliviasculley is working on the Slack form and I believe it was "working" and hosting it for final testing was the task at hand at the meeting earlier this month.

I'll be in touch about an invite to the HG Slack.

**Comment by bogdankharchenko** [comment]
@allella thanks for the invite!

**Comment by zach2825** [comment]
@bogdankharchenko quick question do you use PHPStorm? You can generate an editorconfig and include all the phpstorm settings, that would be so nice.

**Comment by zach2825** [comment]
But, what you have is good if not :+1:

**Comment by bogdankharchenko** [comment]
@zach2825 yes I do. I can certainly commit my code styles but I also want to add a GitHub action to automatically format the code on each pr

**Comment by bogdankharchenko** [comment]
Also @zach2825 ping me on slack, I want to help maintain this repo :)

**Comment by allella** [comment]
Is this read for merge?

**Comment by zach2825** [comment]
I think so, we might want to add on to the .editorconfig in the future, but for now, this is better than nothing.

**Comment by allella** [comment]
Not that I know if these is even applicable, but I am in the process of updating the data.openupstate.org Drupal site and noticed they have a .editorconfig so here's another PHP project if we need ideas

https://github.com/drupal/drupal/blob/9.5.x/.editorconfig

**Pull request merged**
