### PR TITLE
HG#90 cleaned out a bunch of extra unused code and made sure that cancelled events show as cancelled

### LINKED ISSUE #90: Event Calendar - Events often sending you to a 404 page
What: Clicking the event URL from the event details often returns a 404 error.

Steps to Reproduce: Go to the Hackgreenville page and select the [calendar](https://hackgreenville.com/calendar) of events. Randomly select some meetings and visit the url and notice that most take you to a 404 page. It appears that this happens when a recurring meeting is changed, the url continues to point to the old event id url which returns a 404.

### PR DESCRIPTION
**Pull request by zach2825**
fixes #90

I've added code to the calendar page to show the event in red and prepend [CANCELLED] to the title and add. This event has been canceled in the calendar popup, and remove the add to the calendar and visit event URL buttons. 

image

I cleaned up the package and pm2 scripts and cleanout code that will not be used to try to make the project easier to work on. 

Also implemented the cancelled change to the homepage
image

### CODE REVIEW

**Comment by allella** [comment]
Sounds good. If this is ready to go I can merge to develop and test it out on stage.

Are there any Laravel or other commands to run with the changes?

**Review by allella — APPROVED** [review]

**Comment by zach2825** [comment]
Not ready yet I'll change it from draft. I'm wrapping up a change for the events page.

**Comment by zach2825** [comment]
Sorry I thought it was draft already.

**Comment by zach2825** [comment]
ok, it should all be good. This PR is set to merge to develop so we can test in staging. 
image

**Comment by zach2825** [comment]
:+1:  Ready to merge :-D 

please note this will marge the related issue as fixed.

**Comment by zach2825** [comment]
Following a bug reported on the Tersers issues page, they suggested removing node_modules and yarn.lock and re-install with `yarn install` that resolves the issue I saw. So all good now.

**Comment by allella** [comment]
Alright. This is now on stage https://stage.hackgreenville.com/calendar

**Comment by zach2825** [comment]
Awesome! Here too

https://stage.hackgreenville.com/events

**Comment by allella** [comment]
@zach2825 I pulled a release to the master branch and did git pull & yarn install and I'm not seeing the changes on the live site.

The code changes appear to be on the live site and when I switch to the master branch on the stage site it shows the changes too.

Any ideas? Is there a CSS/ JS cache or some other app cache that needs to be cleared on the live site?

image

**Comment by zach2825** [comment]
Run yarn hg:deploy-prep

That runs yarn install and compiles assets

**Comment by allella** [comment]
I ran that and I'm not sure anything changed.

Could you login to the live server and see if I'm missing something obvious?

The changes from the PR appear to be on both servers so I don't think they are out of sync.

**Comment by zach2825** [comment]
We're out at a BBQ right now but I'll check it out later 😃

**Pull request merged**
