### PR TITLE
Explain php artisan serve to contributors

### PR DESCRIPTION
**Pull request by jadelbe418**

### CODE REVIEW

**Comment by allella** [comment]
@zach2825 might have a better suggestion for a localhost server, but merging this in since it should help any newcomers and is better than nothing.

**Comment by zach2825** [comment]
Hello @allella @jadelbe418,

This PR probably needs to be re-created and merged into develop not master. Good idea just needs to go to the correct spot. Maybe we could include this link too? https://laravel.com/docs/5.8/installation#server-requirements

It explains php artisan serve a little.

**Comment by allella** [comment]
@jadelbe418 you have time to submit a PR with Zach's suggestions?

**Comment by zach2825** [comment]
I'm going to create the PR for this code to bring it to develop.

**Comment by jadelbe418** [comment]
I can look at this more this weekend.

**Comment by allella** [comment]
Merged this in, but feel free to do PRs as any improvements or changes are needed.

**Pull request merged**
