### PR TITLE
Carousels and admin ability to manage them.

### PR DESCRIPTION
**Pull request by zach2825**
Trello link - https://trello.com/c/OgT0spWN

you are able to manage the carousel slides from the admin area. When you upload them, for now they save locally. I would like to change it to use the laravel disk so we can easily change it to save on ftp, s3, anywhere without having to change the code. it would just be a config setting at that point.

This PR will be hard to review because it contains all the changes in the other PR after we merge that one you should be able to see these changes easier. 

image

Selection_20191103144003

### CODE REVIEW

**Comment by allella** [comment]
@zach2825 Are you okay with focusing on getting the refactored code stable and up to the live site before merging in more features?

We don't even have a staging site setup yet, so my hope is that I can setup a new subdomain on the existing host and then we can do other PRs to get the site stable before testing and going live.

Once that's live this PR and other features would be easier to view, get feedback from others, and pull live.

**Comment by zach2825** [comment]
Sounds perfect. I'll carry changes from master that contain changes for that one issue and other necessary changes from this PR and create a new PR. should be able to do that relatively quickly.

**Comment by zach2825** [comment]
I'd like to kill this PR. I have been thinking about it a lot and I don't really like the idea of having a carousel on the homepage. If you agree I'm ok with this @allella  PR being closed out.

**Comment by allella** [comment]
We weren't planning on it for this release, but @jeremywight thought a slider might help with the homepage main hero image and headings so we can highlight the different aspects of the IRL side of HG and the online Slack side.

However, we can likely do that with a different image and/or more though on the headings and such.

So, either way a carousel isn't really necessary, as much as it might help with the messaging when we have other audiences or things we're promoting.

@pamelawoodbrowne mentioned economic development visitors as a potential audience we haven't directly tried to accommodate in the early going.

**Comment by zach2825** [comment]
I was just thinking that until we get more content having those images spread out might help make the website look more full

**Comment by allella** [comment]
That's fine. Closing this and we can come back to it when there's a need or time to implement it.

**Comment by allella** [comment]
Relevant to #29 down the  road.

**Pull request closed without merging**
