### PR TITLE
Broken calendar page, missing migrations

### PR DESCRIPTION
**Pull request by zach2825**
Also added an automated test to make sure it does not re-break since its an important page

Those tests create an SQLite database in memory and create and use that database. They will not interfere with existing data in the regular database.

### CODE REVIEW

**Comment by allella** [comment]
Sounds good.

What's the command to run the test(s)?  Also, would/should the tests be called when composer install is run?

**Comment by zach2825** [comment]
You can run the test, after composer install. I can generate the github ci thing so we can run the test automated like. 
It would look like this

```composer install; php artisan test && php artisan migrate```

**Comment by zach2825** [comment]
https://github.com/codeforgreenville/hackgreenville-com/issues/68

**Comment by allella** [comment]
That works. I'm "gasp" new to using CI stuff, but roughly understand the process. This will be a good real-world example for me.

Shall I merge and pull this to stage?

**Comment by zach2825** [comment]
Yes, squash merge is good, thank you :+1: :100: 

Sorry I had some last-minute test updates

**Comment by allella** [comment]
This is up on live and the calendar is working again.

I'll have to find a cancelled event to test that out.

I did get test error, below. Am I missing a dependency, like do I need to make sure SQL Lite is installed on the server?

>    FAIL  Feature\CalendarApiTest
>   ✕ get api calendar events
> 
>   Tests:  1 failed, 2 pending
> 
>    Illuminate\Database\QueryException 
> 
>   could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)

**Pull request merged**
