### PR TITLE
Contact Page: Improve Responsive Design for Mobile, Tablet

### PR DESCRIPTION
**Pull request by bogdankharchenko**
## Before
hackgreenville com_contact

## After
hackgreenville-com test_contact (1)

### CODE REVIEW

**Comment by bogdankharchenko** [comment]
I will need to submit another PR to make changes to the slack join page as well.

**Comment by allella** [comment]
Thanks. @oliviasculley may want to take a look.

**Comment by allella** [comment]
We have a PR for the linter too. https://github.com/codeforgreenville/hackgreenville-com/pull/122

If Zach blesses these things, then we can move forward on them.

**Comment by oliviasculley** [comment]
> This PR is not changing any white space/formatting. The intention is to make the page responsive for Small devices

This PR seems to have a lot of unnecessary indentation changes. I've attached a couple examples from the Github diff UI, but ideally once we have the linter in place then these differences should get linted out

**Comment by bogdankharchenko** [comment]
Oh yea sure. I'm all for linting.

**Comment by allella** [comment]
It looks like the biggest difference is adding the hcaptcha JS file include into the Laravel Blade 'script' stack. Everything else looks like classes and indent changes. 

@oliviasculley if you're good with it then we'll merge.

**Comment by bogdankharchenko** [comment]
I say merge either merge or close this - nothing worse than stale PR's =D

**Comment by oliviasculley** [comment]
Sorry I never replied, it looks good to me but I don't really have any Laravel experience, so if it looks good to you or Zach then I'm good with it :smile:

**Pull request merged**
