### PR TITLE
position homepage content and fix styles page text background colors

### PR DESCRIPTION
**Pull request by zach2825**
This PR contains:
- aligned the new content on the homepage
- yarn and composer update to keep the project up to date
- updated styles page
- added more space around content throughout the site
- set the other main bootstrap colors reference #54 

image

when you pull this down make sure to run `yarn install` and `composer install` to get the updates.

### CODE REVIEW

**Comment by allella** [comment]
Merged. @zach2825  What's the deal with the style guide? Is that visible at a dev only URL or some such?

**Comment by zach2825** [comment]
Yes it's in the foot "our style"

**Comment by allella** [comment]
@zach2825  this is live.

I did note the yarn and composer commands take minutes to run. May be low RAM / going to swap, but it's still pretty bad because it takes the site down when doing a release.

Are there suggested tools / processes to deploy without downtime without having a red / blue load balancer situation?

**Comment by zach2825** [comment]
Good question. I had a project with the same situation I had to upgrade the
server. The other suggestion is to include the build in git but that seems
dangerous to me

**Comment by allella** [comment]
I also added yarn.lock from stage as it generated a new file. I'm assuming we should be tracking yarn.lock in Git, correct?

I think the typical deploy pattern is to pull one server offline, upgrade it, promote it and demote the other instance, upgrade the other instance, and promote it back into the pool.

Except, we don't have multiple instances.

Might just be something we deal with and try to keep the updates smaller.

**Comment by zach2825** [comment]
Yes yarn lock is part of the repo. yarn install should read from the lock
file and install what it had defined.

We probably could build the project in a different directory and copy it
into place. It's quick enough the downtime should be minimal

**Pull request merged**
