### PR TITLE
HG-63 - cleanup canceled events

### LINKED ISSUE #63: Canceled Event Shows on the Calendar and Events Pages
@zach2825  I'm not sure when this event was canceled, but I suspect this could be a case where the local cache/DB for HG is holding on to an event it previously saw in [the API](https://events.openupstate.org/api/gtc), which was later canceled.

https://hackgreenville.com/events
https://hackgreenville.com/calendar

The API doesn't have it listed because I think we're dropping canceled events. Though, are certainly use cases where showing canceled events in the API would allow consumers to show the event as canceled on their end, or choose to discard it.

Pinging @ramonaspence @pamelawoodbrowne @jeremywight for general thoughts on if the events API should retain canceled and then HG should show them in red, or some such.  Or, do we want to keep dumping canceled events and expect the consuming apps to refresh and drop them off?

Here's the Synergy Mill example from this evening.  I though the event was happening because I saw it earlier today on the calendar, but they canceled it at some point.

https://www.meetup.com/synergymill/events/gjnkqrybchbqb/

image

### PR DESCRIPTION
**Pull request by zach2825**
resolves #63

I tried to add @JSn1nj4 as a reviewer but he does not show up in the reviewer's list. 

Added command to fill event_uuids and let the api update the events better and import events missing locations.

To deploy run
```
php artisan migrate;
php artisan events:back-fill-uuid;
php artisan pull:events;
```

The `php artisan events:back-fill-uuid;` command only needs to run one time but it's harmless to keep running it. The goal of that command is to fill the empty event_uuids from the events cache column.

### CODE REVIEW

**Comment by zach2825** [comment]
@allella could you add @JSn1nj4 as a collab for this project. I think that might be why he does not show up. He wants to help :-D

**Comment by allella** [comment]
@zach2825 I added him to the project yesterday. He may need to accept it first.

**Comment by JSn1nj4** [comment]
Sorry about that. I've accepted the invite now.

**Comment by allella** [comment]
I can also merge this into develop and stage it if that helps the process.

Thanks

**Comment by zach2825** [comment]
I'm good with that. There's some notes to do after it's in staging

**Comment by allella** [comment]
@zach2825 I believe this PR is now on stage, but [the calendar is empty](https://stage.hackgreenville.com/calendar) and I don't see an indicator on the cancelled upcoming Code For Greenville event on 2020-10-06 18:00:00 on the [events page](https://stage.hackgreenville.com/events).

I ran the following after merging in the PR.  Are there other caches I need to clear or commands to run?  Thanks

```
git pull && composer install 
php artisan migrate;
php artisan events:back-fill-uuid;
php artisan pull:events;
```

**Comment by allella** [comment]
Actually, the Code For Greenville events are not cancelled in the API. Though, some of them should be cancelled, so we could use them as a test.

Still, I'm not sure on how to resolve the blank calendar issue.

**Pull request merged**
