### PR TITLE
Fun logo work

### PR DESCRIPTION
**Pull request by zach2825**
I created this PR based off of the responses in slack about the logo. This PR is a placeholder until that conversation is done.

### CODE REVIEW

**Comment by zach2825** [comment]
I worked with Tim T. for the error page graphics.

HG-404-2019-11-08 09-58

**Comment by allella** [comment]
Let me know when you want to merge this one.

**Comment by zach2825** [comment]
Good to go now :-D

**Comment by zach2825** [comment]
image

**Pull request merged**
