### PR TITLE
Remove duplicate axios include.

### LINKED ISSUE #34: app.js "Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined"
Javascript error showing in the web browser console on all pages is "Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined"

image

### PR DESCRIPTION
**Pull request by zach2825**
Axios is included in the resources/assets/js/bootstrap.js file which is included in the app.js file in the same directory

resolves #34

### CODE REVIEW

**Comment by allella** [comment]
Sound good, though there's a merge conflict on this PR

```
{
<<<<<<< zach2825/issue-34
    "/js/app.js": "/js/app.js?id=a5d0a9cca6b9508797ef",
    "/css/app.css": "/css/app.css?id=01e447f428a555a48d21"
=======
    "/js/app.js": "/js/app.js?id=28388a4ee114455e030d",
    "/css/app.css": "/css/app.css?id=74a57e7e021e4533b237"
>>>>>>> develop
}
```

**Comment by zach2825** [comment]
I'm sorry that file should be ignored. It's automatically generated

**Comment by allella** [comment]
Cool. Can you submit an updated PR without the conflict?

**Comment by zach2825** [comment]
I can when I get home.. been out all day

**Comment by zach2825** [comment]
resolves #34

**Pull request merged**
