### PR TITLE
Calendar modifications to make the UI better

### PR DESCRIPTION
**Pull request by zach2825**
Selection_20191106133749

### CODE REVIEW

**Comment by allella** [comment]
@zach2825 my preference would be to squash merges to keep the history easier to read.  You cool with that?

**Comment by zach2825** [comment]
I'm not sure what you mean. I can convert this pr to draft or on hold status or something. But I'd like to merge this pr when we're ready to start working features.

**Comment by allella** [comment]
@zach2825 when the last pull request was merged you selected the default to only merge.  There's another option to squash and merge pull requests.

If you have 45 commits in one pull request it will show as one commit in the logs instead of 45.  That's often desirable to keep the logs form having 1000s of commits that say "Changed a work" "Fixed a spelling" and instead you can have a summary message.

**Comment by zach2825** [comment]
Oh I'm dump I see what you mean deleting the feature branch is what I've typically done since that feature branch code and commit history is now in the develop branch. But I'm ok with squashing merges. To be honest I don't know if there's a difference in this case.

**Comment by allella** [comment]
This was a general statement / suggestion and not specific to this PR, but since you merged the last PR I wanted to suggest we also squash.  Most of your PRs have a large number of commits and it's not really necessary to show 20 commit messages for a PR if it really only did one thing and squashing just shows 1 commit message to summarize the commit.

**Comment by zach2825** [comment]
Sounds good thank you.

**Pull request merged**
