### PR TITLE
New Join Slack form

### LINKED ISSUE #47: Change join us on slack page.
Build the page as part of the site. and when people complete the form log the contact in the database and send a slack notification to a "requests" channel or something 

Prerequisite: #46 since we need the slack integration

### LINKED ISSUE #114: Join slack typeform integration is broken
It looks like the referenced typeform url is no longer valid: https://hackgreenville.typeform.com/to/sBMjCF

https://github.com/codeforgreenville/hackgreenville-com/blob/master/resources/views/slack/sign-up.blade.php#L9

Screen Shot 2022-05-28 at 14 45 19

### PR DESCRIPTION
**Pull request by oliviasculley**
Please feel free to add any suggestions, especially for styling!

## Dependencies
This PR heavily builds off of #112, where the contact form is first added, and is branched off of those proposed changes. Thank you!

## Features
- Adds HTML form to join the HackGreenville slack, instead of the Typeform

## Issues
Closes #114 and closes #47

## Preview
Screenshot 2022-06-07 at 20-39-13 HackGreenville Slack Sign-up and Login Info
Screenshot 2022-06-07 at 20-39-28 HackGreenville Slack Sign-up and Login Info
Screenshot 2022-06-07 at 21-17-32 HackGreenville Slack Sign-up and Login Info
Message preview:

### CODE REVIEW

**Comment by allella** [comment]
I'm going to largely defer to @zach2825 for the technical and @Soulfire86 for the operational, but the overall idea of having a simple form that emails a moderator, or else posts to a private or semi-private place in the Slack, makes sense as an alternative to the TypeForm. 

Right now, Andrew Orr is moderating everything that's submitted to https://hackgreenville.com/join-slack and he said it needs to be moderated because he regularly has to weed out spammers and such and occasionally they even pass his Turing Test and end up spamming the Slack.

**Comment by allella** [comment]
Andrew, the moderators group sounds good if we can do it under the free-tier.  @oliviasculley said it can probably go to a private chat, since it would have an ID like a channel, but I wasn't sure if the free-tier has restrictions.

If we do a group moderation I'm imaging that if someone processes the request they can mark it with a specific reactions icon to so others know it's been handled.

**Comment by oliviasculley** [comment]
Actually, now that I think of it, responding to private chats requires a different set of permissions and maybe even api call, so I'm not sure it could work there.
However, it seems that you can make as many private channels on the free tier as you want, so doesn't seem like it would be an issue (https://slack.com/pricing/free?from_pricing=1)
In this PR, the contact and join forms both go to the same slack channel, I'm not sure what settings Laravel has to change that

**Comment by oliviasculley** [comment]
Also, I fixed the errors not showing up for the textbox input, if you noticed that from the screenshots :smile:

**Comment by allella** [comment]
I suppose if we wanted to deploy things to the live server, we could temporarily hide the "Contact" button in the site navigation.

Is there anything holding us up from merging this in an moving closer to real testing, either on the CFG or private Hackgreenvile Slack channel?  Since it's private we might just do it on HackGreenville.

**Comment by oliviasculley** [comment]
I can pretty easily remove the contact stuff from this branch if you'd only want to merge this in, but since they both work in basically the exact same way, there's probably not really a need to deploy both of these independently

**Comment by allella** [comment]
@oliviasculley I should have asked how you'd like to proceed to test this one.  We can merge it in and mess with https://stage.hackgreenville.com

Or, if you want to actually setup the live integration, then I figure we can pull the code to the production server, but we obviously don't want the new forms to show to the end-user until we have the forms working.

**Comment by allella** [comment]
@all-contributors add @oliviasculley for code, ideas, infra, docs, content

**Comment by allella** [comment]
I had to fix a bug that showed up after upgrading the server to PHP 8.1.  Luckily it only took me a few minutes to think to remove /vendors and re-run composer.

I don't think others will run into this unless they were jumping from PHP 7.4 to 8.1

`[2022-08-25 14:43:32] local.ERROR: Target [App\Http\Requests\JoinMessageRequest] is not instantiable.
{"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [App\\Http\\Requests\\JoinMessageRequest] 
 is not instantiable. at /home/username/public_html/hack/vendor/laravel/framework/src/Illuminate/Container/Container.php:1089)
`
I've tested both forms on production and they are working with PHP 8.1 and other server upgrades.

**Pull request merged**
